/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import iss from "./iss.glb"
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function ISS2({ z, ellipseArgs, rate, scale, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(iss)

  const ellipseCurvePoints = new THREE.EllipseCurve(...ellipseArgs)

  useFrame(({ clock }) => {
    let frame = clock.elapsedTime % rate
    let point = ellipseCurvePoints.getPointAt((frame / rate))
    group.current.position.x = point.x
    group.current.position.y = point.y
    group.current.position.z = z


  })



  return (
    <group ref={group} {...props} dispose={null} scale={scale}>
      <mesh geometry={nodes.Cylinder022_7.geometry} material={nodes.Cylinder022_7.material} />
      <mesh geometry={nodes.Cylinder022_8.geometry} material={nodes.Cylinder022_8.material} />
      <mesh geometry={nodes.Cylinder022_9.geometry} material={nodes.Cylinder022_9.material} />
      <mesh geometry={nodes.Cylinder022_10.geometry} material={nodes.Cylinder022_10.material} />
      <group position={[0, 0, -3.38]}>
        <mesh geometry={nodes.Cylinder022_11.geometry} material={nodes.Cylinder022_11.material} />
        <mesh geometry={nodes.Cylinder022_12.geometry} material={nodes.Cylinder022_12.material} />
        <mesh geometry={nodes.Cylinder022_13.geometry} material={nodes.Cylinder022_13.material} />
        <group position={[0, 0.73, -2.46]}>
          <mesh geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} />
          <mesh geometry={nodes.Sphere002_1.geometry} material={nodes.Sphere002_1.material} />
          <mesh geometry={nodes.Sphere002_2.geometry} material={nodes.Sphere002_2.material} />
          <mesh geometry={nodes.Sphere002_3.geometry} material={nodes.Sphere002_3.material} />
          <group position={[0, 0, -12.96]}>
            <mesh geometry={nodes.sm_ext_sm000.geometry} material={nodes.sm_ext_sm000.material} />
            <mesh geometry={nodes.sm_ext_sm000_1.geometry} material={nodes.sm_ext_sm000_1.material} />
            <mesh geometry={nodes.sm_ext_sm000_2.geometry} material={nodes.sm_ext_sm000_2.material} />
            <mesh geometry={nodes.sm_ext_sm000_3.geometry} material={nodes.sm_ext_sm000_3.material} />
            <mesh geometry={nodes.sm_ext_sm000_4.geometry} material={nodes.sm_ext_sm000_4.material} />
            <group position={[0, -1.16, -1.16]}>
              <mesh geometry={nodes.Sphere002_8.geometry} material={nodes.Sphere002_8.material} />
              <mesh geometry={nodes.Sphere002_9.geometry} material={nodes.Sphere002_9.material} />
              <mesh geometry={nodes.Sphere002_10.geometry} material={nodes.Sphere002_10.material} />
              <mesh geometry={nodes.Sphere002_11.geometry} material={nodes.Sphere002_11.material} />
            </group>
            <group position={[0, 1.16, -1.16]}>
              <mesh geometry={nodes.Sphere002_12.geometry} material={nodes.Sphere002_12.material} />
              <mesh geometry={nodes.Sphere002_13.geometry} material={nodes.Sphere002_13.material} />
              <mesh geometry={nodes.Sphere002_14.geometry} material={nodes.Sphere002_14.material} />
              <mesh geometry={nodes.Sphere002_15.geometry} material={nodes.Sphere002_15.material} />
            </group>
            <group position={[2.23, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_5.geometry} material={nodes.sm_ext_sm000_5.material} />
              <mesh geometry={nodes.sm_ext_sm000_6.geometry} material={nodes.sm_ext_sm000_6.material} />
              <mesh geometry={nodes.sm_ext_sm000_7.geometry} material={nodes.sm_ext_sm000_7.material} />
            </group>
            <group position={[-2.23, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_8.geometry} material={nodes.sm_ext_sm000_8.material} />
              <mesh geometry={nodes.sm_ext_sm000_9.geometry} material={nodes.sm_ext_sm000_9.material} />
              <mesh geometry={nodes.sm_ext_sm000_10.geometry} material={nodes.sm_ext_sm000_10.material} />
            </group>
            <group position={[3.51, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_11.geometry} material={nodes.sm_ext_sm000_11.material} />
              <mesh geometry={nodes.sm_ext_sm000_12.geometry} material={nodes.sm_ext_sm000_12.material} />
              <mesh geometry={nodes.sm_ext_sm000_13.geometry} material={nodes.sm_ext_sm000_13.material} />
            </group>
            <group position={[-3.51, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_14.geometry} material={nodes.sm_ext_sm000_14.material} />
              <mesh geometry={nodes.sm_ext_sm000_15.geometry} material={nodes.sm_ext_sm000_15.material} />
              <mesh geometry={nodes.sm_ext_sm000_16.geometry} material={nodes.sm_ext_sm000_16.material} />
            </group>
            <group position={[5.03, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_17.geometry} material={nodes.sm_ext_sm000_17.material} />
              <mesh geometry={nodes.sm_ext_sm000_18.geometry} material={nodes.sm_ext_sm000_18.material} />
              <mesh geometry={nodes.sm_ext_sm000_19.geometry} material={nodes.sm_ext_sm000_19.material} />
            </group>
            <group position={[-5.03, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_20.geometry} material={nodes.sm_ext_sm000_20.material} />
              <mesh geometry={nodes.sm_ext_sm000_21.geometry} material={nodes.sm_ext_sm000_21.material} />
              <mesh geometry={nodes.sm_ext_sm000_22.geometry} material={nodes.sm_ext_sm000_22.material} />
            </group>
            <group position={[6.56, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_23.geometry} material={nodes.sm_ext_sm000_23.material} />
              <mesh geometry={nodes.sm_ext_sm000_24.geometry} material={nodes.sm_ext_sm000_24.material} />
              <mesh geometry={nodes.sm_ext_sm000_25.geometry} material={nodes.sm_ext_sm000_25.material} />
            </group>
            <group position={[-6.56, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_26.geometry} material={nodes.sm_ext_sm000_26.material} />
              <mesh geometry={nodes.sm_ext_sm000_27.geometry} material={nodes.sm_ext_sm000_27.material} />
              <mesh geometry={nodes.sm_ext_sm000_28.geometry} material={nodes.sm_ext_sm000_28.material} />
            </group>
            <group position={[8.07, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_29.geometry} material={nodes.sm_ext_sm000_29.material} />
              <mesh geometry={nodes.sm_ext_sm000_30.geometry} material={nodes.sm_ext_sm000_30.material} />
              <mesh geometry={nodes.sm_ext_sm000_31.geometry} material={nodes.sm_ext_sm000_31.material} />
            </group>
            <group position={[-8.07, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_32.geometry} material={nodes.sm_ext_sm000_32.material} />
              <mesh geometry={nodes.sm_ext_sm000_33.geometry} material={nodes.sm_ext_sm000_33.material} />
              <mesh geometry={nodes.sm_ext_sm000_34.geometry} material={nodes.sm_ext_sm000_34.material} />
            </group>
            <group position={[9.58, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_35.geometry} material={nodes.sm_ext_sm000_35.material} />
              <mesh geometry={nodes.sm_ext_sm000_36.geometry} material={nodes.sm_ext_sm000_36.material} />
              <mesh geometry={nodes.sm_ext_sm000_37.geometry} material={nodes.sm_ext_sm000_37.material} />
            </group>
            <group position={[-9.58, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_38.geometry} material={nodes.sm_ext_sm000_38.material} />
              <mesh geometry={nodes.sm_ext_sm000_39.geometry} material={nodes.sm_ext_sm000_39.material} />
              <mesh geometry={nodes.sm_ext_sm000_40.geometry} material={nodes.sm_ext_sm000_40.material} />
            </group>
            <group position={[11.16, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_41.geometry} material={nodes.sm_ext_sm000_41.material} />
              <mesh geometry={nodes.sm_ext_sm000_42.geometry} material={nodes.sm_ext_sm000_42.material} />
              <mesh geometry={nodes.sm_ext_sm000_43.geometry} material={nodes.sm_ext_sm000_43.material} />
            </group>
            <group position={[-11.16, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_44.geometry} material={nodes.sm_ext_sm000_44.material} />
              <mesh geometry={nodes.sm_ext_sm000_45.geometry} material={nodes.sm_ext_sm000_45.material} />
              <mesh geometry={nodes.sm_ext_sm000_46.geometry} material={nodes.sm_ext_sm000_46.material} />
            </group>
            <group position={[12.74, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_47.geometry} material={nodes.sm_ext_sm000_47.material} />
              <mesh geometry={nodes.sm_ext_sm000_48.geometry} material={nodes.sm_ext_sm000_48.material} />
              <mesh geometry={nodes.sm_ext_sm000_49.geometry} material={nodes.sm_ext_sm000_49.material} />
            </group>
            <group position={[-12.74, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_50.geometry} material={nodes.sm_ext_sm000_50.material} />
              <mesh geometry={nodes.sm_ext_sm000_51.geometry} material={nodes.sm_ext_sm000_51.material} />
              <mesh geometry={nodes.sm_ext_sm000_52.geometry} material={nodes.sm_ext_sm000_52.material} />
            </group>
            <group position={[14.33, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_53.geometry} material={nodes.sm_ext_sm000_53.material} />
              <mesh geometry={nodes.sm_ext_sm000_54.geometry} material={nodes.sm_ext_sm000_54.material} />
              <mesh geometry={nodes.sm_ext_sm000_55.geometry} material={nodes.sm_ext_sm000_55.material} />
            </group>
            <group position={[-14.33, -0.03, -5.26]}>
              <mesh geometry={nodes.sm_ext_sm000_56.geometry} material={nodes.sm_ext_sm000_56.material} />
              <mesh geometry={nodes.sm_ext_sm000_57.geometry} material={nodes.sm_ext_sm000_57.material} />
              <mesh geometry={nodes.sm_ext_sm000_58.geometry} material={nodes.sm_ext_sm000_58.material} />
            </group>
            <mesh
              geometry={nodes.panel_bracket_p.geometry}
              material={nodes.panel_bracket_p.material}
              position={[1.9, -0.03, -5.26]}
            />
            <mesh
              geometry={nodes.panel_bracket_s.geometry}
              material={nodes.panel_bracket_s.material}
              position={[-1.9, -0.03, -5.26]}
            />
          </group>
          <group position={[0, -4.59, -1.15]}>
            <mesh geometry={nodes.Sphere002_4.geometry} material={nodes.Sphere002_4.material} />
            <mesh geometry={nodes.Sphere002_5.geometry} material={nodes.Sphere002_5.material} />
            <mesh geometry={nodes.Sphere002_6.geometry} material={nodes.Sphere002_6.material} />
            <mesh geometry={nodes.Sphere002_7.geometry} material={nodes.Sphere002_7.material} />
          </group>
        </group>
      </group>
      <group position={[0, 1.76, 0]}>
        <mesh geometry={nodes.z1_ext_01001.geometry} material={nodes.z1_ext_01001.material} />
        <mesh geometry={nodes.z1_ext_01001_1.geometry} material={nodes.z1_ext_01001_1.material} />
        <mesh geometry={nodes.z1_ext_01001_2.geometry} material={nodes.z1_ext_01001_2.material} />
        <mesh geometry={nodes.z1_ext_01001_3.geometry} material={materials['ISS_01_dark *']} />
        <mesh geometry={nodes.z1_ext_01001_4.geometry} material={nodes.z1_ext_01001_4.material} />
      </group>
      <group position={[0, 0, 2.22]}>
        <mesh geometry={nodes.Cylinder022_14.geometry} material={nodes.Cylinder022_14.material} />
        <mesh geometry={nodes.Cylinder022_15.geometry} material={nodes.Cylinder022_15.material} />
        <mesh geometry={nodes.Cylinder022_16.geometry} material={nodes.Cylinder022_16.material} />
        <mesh geometry={nodes.Cylinder022_17.geometry} material={nodes.Cylinder022_17.material} />
        <mesh geometry={nodes.Cylinder022_18.geometry} material={nodes.Cylinder022_18.material} />
        <mesh geometry={nodes.Cylinder022_19.geometry} material={nodes.Cylinder022_19.material} />
        <group position={[2.73, -0.48, 2.01]}>
          <mesh geometry={nodes.z1_ext_01001_5.geometry} material={nodes.z1_ext_01001_5.material} />
          <mesh geometry={nodes.z1_ext_01001_6.geometry} material={nodes.z1_ext_01001_6.material} />
        </group>
        <group position={[0, 5.01, 0.97]}>
          <mesh geometry={nodes.s0_ani000.geometry} material={nodes.s0_ani000.material} />
          <mesh geometry={nodes.s0_ani000_1.geometry} material={nodes.s0_ani000_1.material} />
          <mesh geometry={nodes.s0_ani000_2.geometry} material={nodes.s0_ani000_2.material} />
          <mesh geometry={nodes.s0_ani000_3.geometry} material={nodes.s0_ani000_3.material} />
          <mesh geometry={nodes.s0_ani000_4.geometry} material={nodes.s0_ani000_4.material} />
          <group position={[-2.87, -0.6, 5.17]}>
            <mesh geometry={nodes.mss_mbs001.geometry} material={nodes.mss_mbs001.material} />
            <mesh geometry={nodes.mss_mbs001_1.geometry} material={nodes.mss_mbs001_1.material} />
            <mesh geometry={nodes.mss_mbs001_2.geometry} material={nodes.mss_mbs001_2.material} />
            <mesh geometry={nodes.mss_mbs001_3.geometry} material={nodes.mss_mbs001_3.material} />
            <mesh
              geometry={nodes['11_Canadarm2'].geometry}
              material={nodes['11_Canadarm2'].material}
              position={[-1.43, 1.59, 0.2]}>
              <mesh
                geometry={nodes['11_Canadarm2_02'].geometry}
                material={nodes['11_Canadarm2_02'].material}
                position={[-0.67, 0.36, 0.98]}>
                <mesh
                  geometry={nodes['11_Canadarm2_03'].geometry}
                  material={nodes['11_Canadarm2_03'].material}
                  position={[-0.01, 0.36, 0.23]}>
                  <mesh
                    geometry={nodes['11_Canadarm2_04'].geometry}
                    material={nodes['11_Canadarm2_04'].material}
                    position={[0.13, 0.25, 0.31]}>
                    <mesh
                      geometry={nodes['11_Canadarm2_05'].geometry}
                      material={nodes['11_Canadarm2_05'].material}
                      position={[-7.34, 0, 0.58]}>
                      <mesh
                        geometry={nodes['11_Canadarm2_06'].geometry}
                        material={nodes['11_Canadarm2_06'].material}
                        position={[0, 7.34, 0.58]}>
                        <mesh
                          geometry={nodes['11_Canadarm2_07'].geometry}
                          material={nodes['11_Canadarm2_07'].material}
                          position={[-0.29, 0, 0.31]}>
                          <mesh
                            geometry={nodes['11_Canadarm2_08'].geometry}
                            material={nodes['11_Canadarm2_08'].material}
                            position={[-0.31, 0.29, 0]}>
                            <group position={[0, 1.2, 0]}>
                              <mesh geometry={nodes.Cylinder022_83.geometry} material={nodes.Cylinder022_83.material} />
                              <mesh geometry={nodes.Cylinder022_84.geometry} material={nodes.Cylinder022_84.material} />
                              <mesh
                                geometry={nodes['29_DEXTRE001'].geometry}
                                material={nodes['29_DEXTRE001'].material}
                                position={[0, 0.22, 0]}>
                                <mesh
                                  geometry={nodes['29_DEXTRE002'].geometry}
                                  material={nodes['29_DEXTRE002'].material}
                                  position={[0, 1.96, 0.01]}>
                                  <mesh
                                    geometry={nodes['29_DEXTRE003'].geometry}
                                    material={nodes['29_DEXTRE003'].material}
                                    position={[0, 0.96, 0]}
                                  />
                                </mesh>
                                <mesh
                                  geometry={nodes['29_DEXTRE004'].geometry}
                                  material={nodes['29_DEXTRE004'].material}
                                  position={[1.38, 1.43, 0]}>
                                  <mesh
                                    geometry={nodes['29_DEXTRE005'].geometry}
                                    material={nodes['29_DEXTRE005'].material}
                                    position={[0.37, -0.1, 0.27]}>
                                    <mesh
                                      geometry={nodes['29_DEXTRE006'].geometry}
                                      material={nodes['29_DEXTRE006'].material}
                                      position={[0.3, -0.11, 0.14]}>
                                      <mesh
                                        geometry={nodes['29_DEXTRE007'].geometry}
                                        material={nodes['29_DEXTRE007'].material}
                                        position={[1.09, 0.01, 0.06]}>
                                        <mesh
                                          geometry={nodes['29_DEXTRE008'].geometry}
                                          material={nodes['29_DEXTRE008'].material}
                                          position={[1.09, -0.01, -0.33]}>
                                          <mesh
                                            geometry={nodes['29_DEXTRE009'].geometry}
                                            material={nodes['29_DEXTRE009'].material}
                                            position={[0.28, -0.12, -0.11]}
                                          />
                                        </mesh>
                                      </mesh>
                                    </mesh>
                                  </mesh>
                                </mesh>
                                <mesh
                                  geometry={nodes['29_DEXTRE010'].geometry}
                                  material={nodes['29_DEXTRE010'].material}
                                  position={[-1.38, 1.43, 0]}>
                                  <mesh
                                    geometry={nodes['29_DEXTRE011'].geometry}
                                    material={nodes['29_DEXTRE011'].material}
                                    position={[-0.37, -0.1, 0.27]}>
                                    <mesh
                                      geometry={nodes['29_DEXTRE012'].geometry}
                                      material={nodes['29_DEXTRE012'].material}
                                      position={[-0.3, -0.11, 0.14]}>
                                      <mesh
                                        geometry={nodes['29_DEXTRE013'].geometry}
                                        material={nodes['29_DEXTRE013'].material}
                                        position={[-1.09, 0.01, 0.06]}>
                                        <mesh
                                          geometry={nodes['29_DEXTRE014'].geometry}
                                          material={nodes['29_DEXTRE014'].material}
                                          position={[-1.09, -0.01, -0.33]}>
                                          <mesh
                                            geometry={nodes['29_DEXTRE015'].geometry}
                                            material={nodes['29_DEXTRE015'].material}
                                            position={[-0.28, -0.12, -0.11]}
                                          />
                                        </mesh>
                                      </mesh>
                                    </mesh>
                                  </mesh>
                                </mesh>
                              </mesh>
                            </group>
                          </mesh>
                        </mesh>
                      </mesh>
                    </mesh>
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
          </group>
          <group position={[-13.81, 0, 2.44]}>
            <mesh geometry={nodes.s0_ani000_5.geometry} material={nodes.s0_ani000_5.material} />
            <mesh geometry={nodes.s0_ani000_6.geometry} material={nodes.s0_ani000_6.material} />
            <mesh geometry={nodes.s0_ani000_7.geometry} material={nodes.s0_ani000_7.material} />
            <mesh geometry={nodes.s0_ani000_8.geometry} material={nodes.s0_ani000_8.material} />
            <mesh geometry={nodes.s0_ani000_9.geometry} material={nodes.s0_ani000_9.material} />
            <group position={[-1.44, -0.01, -0.94]}>
              <mesh geometry={nodes.s0_ani000_15.geometry} material={nodes.s0_ani000_15.material} />
              <mesh geometry={nodes.s0_ani000_16.geometry} material={nodes.s0_ani000_16.material} />
              <mesh geometry={nodes.s0_ani000_17.geometry} material={nodes.s0_ani000_17.material} />
              <mesh geometry={nodes.s0_ani000_18.geometry} material={nodes.s0_ani000_18.material} />
            </group>
            <group position={[-10.05, 0.01, -0.82]}>
              <mesh geometry={nodes.s0_ani000_19.geometry} material={nodes.s0_ani000_19.material} />
              <mesh geometry={nodes.s0_ani000_20.geometry} material={nodes.s0_ani000_20.material} />
              <mesh geometry={nodes.s0_ani000_21.geometry} material={nodes.s0_ani000_21.material} />
              <group position={[-3.02, -0.03, -0.01]} rotation={[Math.PI / 3, 0, 0]}>
                <mesh geometry={nodes.p6_ani000.geometry} material={nodes.p6_ani000.material} />
                <mesh geometry={nodes.p6_ani000_1.geometry} material={nodes.p6_ani000_1.material} />
                <mesh geometry={nodes.p6_ani000_2.geometry} material={nodes.p6_ani000_2.material} />
                <mesh geometry={nodes.p6_ani000_3.geometry} material={nodes.p6_ani000_3.material} />
                <mesh geometry={nodes.p6_ani000_4.geometry} material={nodes.p6_ani000_4.material} />
                <group position={[-8.14, -0.01, 1.23]}>
                  <mesh geometry={nodes.Cube008_46.geometry} material={nodes.Cube008_46.material} />
                  <mesh geometry={nodes.Cube008_47.geometry} material={nodes.Cube008_47.material} />
                  <mesh geometry={nodes.Cube008_48.geometry} material={nodes.Cube008_48.material} />
                  <mesh geometry={nodes.Cube008_49.geometry} material={nodes.Cube008_49.material} />
                  <group position={[0.49, 0.68, 0.67]}>
                    <mesh geometry={nodes.p6_ani000_10.geometry} material={nodes.p6_ani000_10.material} />
                    <mesh geometry={nodes.p6_ani000_11.geometry} material={nodes.p6_ani000_11.material} />
                    <mesh geometry={nodes.p6_ani000_12.geometry} material={nodes.p6_ani000_12.material} />
                  </group>
                  <group position={[0.49, -0.68, -2.39]}>
                    <mesh geometry={nodes.p6_ani000_13.geometry} material={nodes.p6_ani000_13.material} />
                    <mesh geometry={nodes.p6_ani000_14.geometry} material={nodes.p6_ani000_14.material} />
                    <mesh geometry={nodes.p6_ani000_15.geometry} material={nodes.p6_ani000_15.material} />
                  </group>
                  <group position={[-1.44, 0, -0.85]}>
                    <mesh geometry={nodes.p6_ani000_16.geometry} material={nodes.p6_ani000_16.material} />
                    <mesh geometry={nodes.p6_ani000_17.geometry} material={nodes.p6_ani000_17.material} />
                    <mesh geometry={nodes.p6_ani000_18.geometry} material={nodes.p6_ani000_18.material} />
                    <mesh geometry={nodes.p6_ani000_19.geometry} material={nodes.p6_ani000_19.material} />
                    <group position={[-13.49, 0.68, 1.52]}>
                      <mesh geometry={nodes.p6_ani000_30.geometry} material={nodes.p6_ani000_30.material} />
                      <mesh geometry={nodes.p6_ani000_31.geometry} material={nodes.p6_ani000_31.material} />
                      <mesh geometry={nodes.p6_ani000_32.geometry} material={nodes.p6_ani000_32.material} />
                    </group>
                    <group position={[-13.49, -0.68, -1.53]}>
                      <mesh geometry={nodes.p6_ani000_33.geometry} material={nodes.p6_ani000_33.material} />
                      <mesh geometry={nodes.p6_ani000_34.geometry} material={nodes.p6_ani000_34.material} />
                      <mesh geometry={nodes.p6_ani000_35.geometry} material={nodes.p6_ani000_35.material} />
                    </group>
                  </group>
                </group>
              </group>
              <group position={[-1.31, -2.25, 0]}>
                <mesh geometry={nodes.ESP3000.geometry} material={nodes.ESP3000.material} />
                <mesh geometry={nodes.ESP3000_1.geometry} material={nodes.ESP3000_1.material} />
                <mesh geometry={nodes.ESP3000_2.geometry} material={nodes.ESP3000_2.material} />
                <mesh geometry={nodes.ESP3000_3.geometry} material={nodes.ESP3000_3.material} />
                <mesh geometry={nodes.ESP3000_4.geometry} material={nodes.ESP3000_4.material} />
              </group>
              <group position={[-1.84, 5.06, 0]}>
                <mesh geometry={nodes.esp2_lo000_4.geometry} material={nodes.esp2_lo000_4.material} />
                <mesh geometry={nodes.esp2_lo000_5.geometry} material={nodes.esp2_lo000_5.material} />
                <mesh geometry={nodes.esp2_lo000_6.geometry} material={nodes.esp2_lo000_6.material} />
                <mesh geometry={nodes.esp2_lo000_7.geometry} material={nodes.esp2_lo000_7.material} />
              </group>
              <group position={[2.21, -5.07, 0]}>
                <mesh geometry={nodes.esp2_lo000_8.geometry} material={nodes.esp2_lo000_8.material} />
                <mesh geometry={nodes.esp2_lo000_9.geometry} material={nodes.esp2_lo000_9.material} />
                <mesh geometry={nodes.esp2_lo000_10.geometry} material={nodes.esp2_lo000_10.material} />
              </group>
              <group position={[2.11, 3.72, -0.24]}>
                <mesh geometry={nodes.AMS2000.geometry} material={nodes.AMS2000.material} />
                <mesh geometry={nodes.AMS2000_1.geometry} material={nodes.AMS2000_1.material} />
                <mesh geometry={nodes.AMS2000_2.geometry} material={nodes.AMS2000_2.material} />
              </group>
            </group>
            <group position={[2.68, 1.91, 0.13]}>
              <mesh geometry={nodes.Cylinder022_63.geometry} material={nodes.Cylinder022_63.material} />
              <mesh geometry={nodes.Cylinder022_64.geometry} material={nodes.Cylinder022_64.material} />
              <mesh geometry={nodes.Cylinder022_65.geometry} material={nodes.Cylinder022_65.material} />
            </group>
          </group>
          <group position={[6.82, 2.24, 1.5]}>
            <mesh geometry={nodes.s0_ani000_10.geometry} material={nodes.s0_ani000_10.material} />
            <mesh geometry={nodes.s0_ani000_11.geometry} material={nodes.s0_ani000_11.material} />
            <mesh geometry={nodes.s0_ani000_12.geometry} material={nodes.s0_ani000_12.material} />
            <mesh geometry={nodes.s0_ani000_13.geometry} material={nodes.s0_ani000_13.material} />
            <mesh geometry={nodes.s0_ani000_14.geometry} material={nodes.s0_ani000_14.material} />
            <group position={[8.43, -2.23, -0.01]}>
              <mesh geometry={nodes.s0_ani000_22.geometry} material={nodes.s0_ani000_22.material} />
              <mesh geometry={nodes.s0_ani000_23.geometry} material={nodes.s0_ani000_23.material} />
              <mesh geometry={nodes.s0_ani000_24.geometry} material={nodes.s0_ani000_24.material} />
              <mesh geometry={nodes.s0_ani000_25.geometry} material={nodes.s0_ani000_25.material} />
            </group>
            <group position={[17.04, -2.23, 0.11]}>
              <mesh geometry={nodes.s0_ani000_26.geometry} material={nodes.s0_ani000_26.material} />
              <mesh geometry={nodes.s0_ani000_27.geometry} material={nodes.s0_ani000_27.material} />
              <mesh geometry={nodes.s0_ani000_28.geometry} material={nodes.s0_ani000_28.material} />
              <group position={[3.02, 0.01, -0.03]} rotation={[Math.PI / 3, 0, 0]}>
                <mesh geometry={nodes.p6_ani000_5.geometry} material={nodes.p6_ani000_5.material} />
                <mesh geometry={nodes.p6_ani000_6.geometry} material={nodes.p6_ani000_6.material} />
                <mesh geometry={nodes.p6_ani000_7.geometry} material={nodes.p6_ani000_7.material} />
                <mesh geometry={nodes.p6_ani000_8.geometry} material={nodes.p6_ani000_8.material} />
                <mesh geometry={nodes.p6_ani000_9.geometry} material={nodes.p6_ani000_9.material} />
                <group position={[8.14, -0.01, -1.23]}>
                  <mesh geometry={nodes.Cube008_50.geometry} material={nodes.Cube008_50.material} />
                  <mesh geometry={nodes.Cube008_51.geometry} material={nodes.Cube008_51.material} />
                  <mesh geometry={nodes.Cube008_52.geometry} material={nodes.Cube008_52.material} />
                  <mesh geometry={nodes.Cube008_53.geometry} material={nodes.Cube008_53.material} />
                  <group position={[1.44, 0, 0.85]}>
                    <mesh geometry={nodes.p6_ani000_20.geometry} material={nodes.p6_ani000_20.material} />
                    <mesh geometry={nodes.p6_ani000_21.geometry} material={nodes.p6_ani000_21.material} />
                    <mesh geometry={nodes.p6_ani000_22.geometry} material={nodes.p6_ani000_22.material} />
                    <mesh geometry={nodes.p6_ani000_23.geometry} material={nodes.p6_ani000_23.material} />
                    <group position={[13.49, -0.68, 1.53]}>
                      <mesh geometry={nodes.p6_ani000_36.geometry} material={nodes.p6_ani000_36.material} />
                      <mesh geometry={nodes.p6_ani000_37.geometry} material={nodes.p6_ani000_37.material} />
                      <mesh geometry={nodes.p6_ani000_38.geometry} material={nodes.p6_ani000_38.material} />
                    </group>
                    <group position={[13.49, 0.68, -1.52]}>
                      <mesh geometry={nodes.p6_ani000_39.geometry} material={nodes.p6_ani000_39.material} />
                      <mesh geometry={nodes.p6_ani000_40.geometry} material={nodes.p6_ani000_40.material} />
                      <mesh geometry={nodes.p6_ani000_41.geometry} material={nodes.p6_ani000_41.material} />
                    </group>
                  </group>
                  <group position={[-0.49, -0.68, 2.39]}>
                    <mesh geometry={nodes.p6_ani000_24.geometry} material={nodes.p6_ani000_24.material} />
                    <mesh geometry={nodes.p6_ani000_25.geometry} material={nodes.p6_ani000_25.material} />
                    <mesh geometry={nodes.p6_ani000_26.geometry} material={nodes.p6_ani000_26.material} />
                  </group>
                  <group position={[-0.49, 0.68, -0.67]}>
                    <mesh geometry={nodes.p6_ani000_27.geometry} material={nodes.p6_ani000_27.material} />
                    <mesh geometry={nodes.p6_ani000_28.geometry} material={nodes.p6_ani000_28.material} />
                    <mesh geometry={nodes.p6_ani000_29.geometry} material={nodes.p6_ani000_29.material} />
                  </group>
                </group>
              </group>
              <group position={[1.06, -5.07, -0.04]}>
                <mesh geometry={nodes.esp2_lo000_11.geometry} material={nodes.esp2_lo000_11.material} />
                <mesh geometry={nodes.esp2_lo000_12.geometry} material={nodes.esp2_lo000_12.material} />
                <mesh geometry={nodes.esp2_lo000_13.geometry} material={nodes.esp2_lo000_13.material} />
                <mesh geometry={nodes.esp2_lo000_14.geometry} material={nodes.esp2_lo000_14.material} />
              </group>
              <group position={[1.84, 5.06, -0.07]}>
                <mesh geometry={nodes.esp2_lo000_15.geometry} material={materials.ISS_AO_08} />
                <mesh geometry={nodes.esp2_lo000_16.geometry} material={nodes.esp2_lo000_16.material} />
                <mesh geometry={nodes.esp2_lo000_17.geometry} material={nodes.esp2_lo000_17.material} />
                <mesh geometry={nodes.esp2_lo000_18.geometry} material={nodes.esp2_lo000_18.material} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, 0, 9.16]}>
          <mesh geometry={nodes.Cylinder022_36.geometry} material={nodes.Cylinder022_36.material} />
          <mesh geometry={nodes.Cylinder022_37.geometry} material={nodes.Cylinder022_37.material} />
          <mesh geometry={nodes.Cylinder022_38.geometry} material={nodes.Cylinder022_38.material} />
          <mesh geometry={nodes.Cylinder022_39.geometry} material={nodes.Cylinder022_39.material} />
          <group position={[0, 0, 6.97]}>
            <mesh geometry={nodes.Cylinder022_46.geometry} material={nodes.Cylinder022_46.material} />
            <mesh geometry={nodes.Cylinder022_47.geometry} material={nodes.Cylinder022_47.material} />
            <mesh geometry={nodes.Cylinder022_48.geometry} material={nodes.Cylinder022_48.material} />
          </group>
          <group position={[-4.17, 0, 4.83]}>
            <mesh geometry={nodes.Cylinder022_49.geometry} material={nodes.Cylinder022_49.material} />
            <mesh geometry={nodes.Cylinder022_50.geometry} material={nodes.Cylinder022_50.material} />
            <mesh geometry={nodes.Cylinder022_51.geometry} material={nodes.Cylinder022_51.material} />
            <mesh geometry={nodes.Cylinder022_52.geometry} material={nodes.Cylinder022_52.material} />
            <mesh geometry={nodes.Cylinder022_53.geometry} material={nodes.Cylinder022_53.material} />
            <mesh geometry={nodes.Cylinder022_54.geometry} material={nodes.Cylinder022_54.material} />
            <group position={[-5.9, -1.33, 0]}>
              {/* <mesh geometry={nodes.Cube008_35.geometry} material={nodes.Cube008_35.material} /> */}
              <mesh geometry={nodes.Cube008_36.geometry} material={nodes.Cube008_36.material} />
              <mesh geometry={nodes.Cube008_37.geometry} material={nodes.Cube008_37.material} />
              <mesh geometry={nodes.Cube008_38.geometry} material={nodes.Cube008_38.material} />
              <mesh
                geometry={nodes.RapidScat_dish.geometry}
                material={nodes.RapidScat_dish.material}
                position={[-0.73, -0.83, -0.22]}
              />
            </group>
          </group>
          <group position={[7.48, 0, 4.83]}>
            <mesh geometry={nodes.Cylinder022_55.geometry} material={nodes.Cylinder022_55.material} />
            <mesh geometry={nodes.Cylinder022_56.geometry} material={nodes.Cylinder022_56.material} />
            <mesh geometry={nodes.Cylinder022_57.geometry} material={nodes.Cylinder022_57.material} />
            <mesh geometry={nodes.Cylinder022_58.geometry} material={nodes.Cylinder022_58.material} />
            <mesh geometry={nodes.Cylinder022_59.geometry} material={nodes.Cylinder022_59.material} />
            <mesh geometry={nodes.Cylinder022_60.geometry} material={nodes.Cylinder022_60.material} />
            <group position={[2.82, 4.04, 0]}>
              <mesh geometry={nodes.Cylinder022_66.geometry} material={nodes.Cylinder022_66.material} />
              {/* <mesh geometry={nodes.Cylinder022_67.geometry} material={nodes.Cylinder022_67.material} /> */}
              {/* <mesh geometry={nodes.Cylinder022_68.geometry} material={nodes.Cylinder022_68.material} /> */}
              {/* <mesh geometry={nodes.Cylinder022_69.geometry} material={nodes.Cylinder022_69.material} /> */}
              {/* <mesh geometry={nodes.Cylinder022_70.geometry} material={nodes.Cylinder022_70.material} /> */}
              {/* <mesh geometry={nodes.Cylinder022_71.geometry} material={nodes.Cylinder022_71.material} /> */}
            </group>
            <mesh
              geometry={nodes['31_Robotic_Arm'].geometry}
              material={nodes['31_Robotic_Arm'].material}
              position={[5.14, 0.88, 1.68]}>
              <mesh
                geometry={nodes['31_Robotic_Arm001'].geometry}
                material={nodes['31_Robotic_Arm001'].material}
                position={[0.76, 0.3, -0.33]}>
                <mesh
                  geometry={nodes['31_Robotic_Arm002'].geometry}
                  material={nodes['31_Robotic_Arm002'].material}
                  position={[0, 0.41, 0.53]}>
                  <mesh
                    geometry={nodes['31_Robotic_Arm003'].geometry}
                    material={nodes['31_Robotic_Arm003'].material}
                    position={[4.07, 0, -0.54]}>
                    <mesh
                      geometry={nodes['31_Robotic_Arm004'].geometry}
                      material={nodes['31_Robotic_Arm004'].material}
                      position={[4.07, 0, -0.52]}>
                      <mesh
                        geometry={nodes['31_Robotic_Arm005'].geometry}
                        material={nodes['31_Robotic_Arm005'].material}
                        position={[0.44, 0.52, 0.01]}
                      />
                    </mesh>
                  </mesh>
                </mesh>
              </mesh>
            </mesh>
            <group position={[6.05, -1.56, -0.09]}>
              <mesh geometry={nodes.Cube008_39.geometry} material={nodes.Cube008_39.material} />
              <mesh geometry={nodes.Cube008_40.geometry} material={nodes.Cube008_40.material} />
              <mesh geometry={nodes.Cube008_41.geometry} material={nodes.Cube008_41.material} />
              <mesh geometry={nodes.Cube008_42.geometry} material={nodes.Cube008_42.material} />
            </group>
            <group position={[10.49, -1.95, -1.08]}>
              <mesh geometry={nodes.Cube008_43.geometry} material={nodes.Cube008_43.material} />
              {/* <mesh geometry={nodes.Cube008_44.geometry} material={nodes.Cube008_44.material} /> */}
            </group>
          </group>
        </group>
        <mesh
          geometry={nodes.Destiny_Window_Cover.geometry}
          material={nodes.Destiny_Window_Cover.material}
          position={[0, -2.32, 4.78]}
        />
      </group>
      <group position={[-3.69, -0.37, 0]}>
        <mesh geometry={nodes.Cylinder022_20.geometry} material={nodes.Cylinder022_20.material} />
        <mesh geometry={nodes.Cylinder022_21.geometry} material={nodes.Cylinder022_21.material} />
        <mesh geometry={nodes.Cylinder022_22.geometry} material={nodes.Cylinder022_22.material} />
        <mesh geometry={nodes.Cylinder022_23.geometry} material={nodes.Cylinder022_23.material} />
        <mesh geometry={nodes.Cylinder022_24.geometry} material={nodes.Cylinder022_24.material} />
        <mesh geometry={nodes.Cylinder022_25.geometry} material={nodes.Cylinder022_25.material} />
        <mesh geometry={nodes.Cylinder022_26.geometry} material={nodes.Cylinder022_26.material} />
        <group position={[0.64, 0, 2.43]}>
          <mesh geometry={nodes.esp2_lo000.geometry} material={nodes.esp2_lo000.material} />
          <mesh geometry={nodes.esp2_lo000_1.geometry} material={nodes.esp2_lo000_1.material} />
          <mesh geometry={nodes.esp2_lo000_2.geometry} material={nodes.esp2_lo000_2.material} />
          <mesh geometry={nodes.esp2_lo000_3.geometry} material={nodes.esp2_lo000_3.material} />
        </group>
      </group>
      <group position={[2.23, 0, 0]}>
        <mesh geometry={nodes.Cylinder022_27.geometry} material={nodes.Cylinder022_27.material} />
        <mesh geometry={nodes.Cylinder022_28.geometry} material={nodes.Cylinder022_28.material} />
        <mesh geometry={nodes.Cylinder022_29.geometry} material={nodes.Cylinder022_29.material} />
        <mesh geometry={nodes.Cylinder022_30.geometry} material={nodes.Cylinder022_30.material} />
        <group position={[6.97, 0, 0]}>
          <mesh geometry={nodes.Cylinder022_40.geometry} material={nodes.Cylinder022_40.material} />
          <mesh geometry={nodes.Cylinder022_41.geometry} material={nodes.Cylinder022_41.material} />
          <mesh geometry={nodes.Cylinder022_42.geometry} material={nodes.Cylinder022_42.material} />
        </group>
        <group position={[4.83, -2.62, 0]}>
          <mesh geometry={nodes.Cylinder022_43.geometry} material={nodes.Cylinder022_43.material} />
          <mesh geometry={nodes.Cylinder022_44.geometry} material={nodes.Cylinder022_44.material} />
          <mesh geometry={nodes.Cylinder022_45.geometry} material={nodes.Cylinder022_45.material} />
          <mesh
            geometry={nodes['38_Cupola001'].geometry}
            material={nodes['38_Cupola001'].material}
            position={[1.2, -0.36, -0.01]}
          />
          <mesh
            geometry={nodes['38_Cupola002'].geometry}
            material={nodes['38_Cupola002'].material}
            position={[0.58, -0.36, 1.05]}
          />
          <mesh
            geometry={nodes['38_Cupola003'].geometry}
            material={nodes['38_Cupola003'].material}
            position={[-0.57, -0.36, 1.05]}
          />
          <mesh
            geometry={nodes['38_Cupola004'].geometry}
            material={nodes['38_Cupola004'].material}
            position={[-1.2, -0.36, 0]}
          />
          <mesh
            geometry={nodes['38_Cupola005'].geometry}
            material={nodes['38_Cupola005'].material}
            position={[-0.58, -0.36, -1.05]}
          />
          <mesh
            geometry={nodes['38_Cupola006'].geometry}
            material={nodes['38_Cupola006'].material}
            position={[0.62, -0.36, -1.03]}
          />
          <mesh
            geometry={nodes['38_Cupola007'].geometry}
            material={nodes['38_Cupola007'].material}
            position={[-0.62, -1.05, 0.3]}
          />
          <mesh geometry={nodes.ISS.geometry} material={nodes.ISS.material} position={[0, -0.02, 0]} />
        </group>
      </group>
      <group position={[0, -2.19, 0]}>
        <mesh geometry={nodes.Cylinder022_31.geometry} material={nodes.Cylinder022_31.material} />
        <mesh geometry={nodes.Cylinder022_32.geometry} material={nodes.Cylinder022_32.material} />
        <mesh geometry={nodes.Cylinder022_33.geometry} material={nodes.Cylinder022_33.material} />
        <mesh geometry={nodes.Cylinder022_34.geometry} material={nodes.Cylinder022_34.material} />
        <mesh geometry={nodes.Cylinder022_35.geometry} material={nodes.Cylinder022_35.material} />
      </group>
      <group position={[1.69, 0.85, -11.09]}>
        {/* <mesh geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} /> */}
        {/* <mesh geometry={nodes.Cube008_1.geometry} material={nodes.Cube008_1.material} /> */}
      </group>
      <mesh geometry={nodes.hinge_02_p.geometry} material={nodes.hinge_02_p.material} position={[2.17, 0.8, -12.51]} />
      <group position={[2.94, 0.8, -9.63]}>
        {/* <mesh geometry={nodes.Cube008_3.geometry} material={nodes.Cube008_3.material} /> */}
        {/* <mesh geometry={nodes.Cube008_4.geometry} material={nodes.Cube008_4.material} /> */}
      </group>
      <mesh geometry={nodes.hinge_04_p.geometry} material={nodes.hinge_04_p.material} position={[3.91, 0.8, -12.5]} />
      <mesh geometry={nodes.hinge_01_p.geometry} material={nodes.hinge_01_p.material} position={[1.69, 0.8, -11.09]} />
      <group position={[2.17, 0.8, -9.66]}>
        {/* <mesh geometry={nodes.Cube008_7.geometry} material={nodes.Cube008_7.material} /> */}
        <mesh geometry={nodes.Cube008_8.geometry} material={nodes.Cube008_8.material} />
      </group>
      <mesh geometry={nodes.hinge_03_p.geometry} material={nodes.hinge_03_p.material} position={[2.93, 0.8, -12.54]} />
      <group position={[3.91, 0.8, -9.68]}>
        <mesh geometry={nodes.Cube008_10.geometry} material={nodes.Cube008_10.material} />
        <mesh geometry={nodes.Cube008_11.geometry} material={nodes.Cube008_11.material} />
      </group>
      <group position={[-1.69, 0.85, -11.09]}>
        <mesh geometry={nodes.Cube008_12.geometry} material={nodes.Cube008_12.material} />
        <mesh geometry={nodes.Cube008_13.geometry} material={nodes.Cube008_13.material} />
      </group>
      <mesh geometry={nodes.hinge_02_s.geometry} material={nodes.hinge_02_s.material} position={[-2.17, 0.8, -12.51]} />
      <group position={[-2.94, 0.8, -9.63]}>
        <mesh geometry={nodes.Cube008_15.geometry} material={nodes.Cube008_15.material} />
        <mesh geometry={nodes.Cube008_16.geometry} material={nodes.Cube008_16.material} />
      </group>
      <mesh geometry={nodes.hinge_04_s.geometry} material={nodes.hinge_04_s.material} position={[-3.91, 0.8, -12.5]} />
      <mesh geometry={nodes.hinge_03_s.geometry} material={nodes.hinge_03_s.material} position={[-2.93, 0.8, -12.54]} />
      <group position={[-3.91, 0.8, -9.68]}>
        <mesh geometry={nodes.Cube008_19.geometry} material={nodes.Cube008_19.material} />
        <mesh geometry={nodes.Cube008_20.geometry} material={nodes.Cube008_20.material} />
      </group>
      <group position={[-2.17, 0.8, -9.66]}>
        <mesh geometry={nodes.Cube008_21.geometry} material={nodes.Cube008_21.material} />
        <mesh geometry={nodes.Cube008_22.geometry} material={nodes.Cube008_22.material} />
      </group>
      <mesh geometry={nodes.hinge_01_s.geometry} material={nodes.hinge_01_s.material} position={[-1.69, 0.8, -11.09]} />
      <group position={[15.53, -2.12, 19.9]}>
        <mesh geometry={nodes.Cube008_24.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube008_25.geometry} material={materials.base_metal} />
        <mesh geometry={nodes.Cube008_26.geometry} material={nodes.Cube008_26.material} />
        <mesh geometry={nodes.Cube008_27.geometry} material={materials['ISS_03_dull.001']} />
      </group>
      <group position={[18.91, -1.96, 16.11]}>
        <mesh geometry={nodes.Cylinder022.geometry} material={materials.ecostress} />
        <mesh geometry={nodes.Cylinder022_1.geometry} material={materials['plastic black']} />
        <mesh geometry={nodes.Cylinder022_2.geometry} material={materials.ecostressWhite} />
        <mesh geometry={nodes.Cylinder022_3.geometry} material={materials['ISS_03_dull.002']} />
        <mesh geometry={nodes.Cylinder022_4.geometry} material={materials['ecostress metal']} />
        <mesh geometry={nodes.Cylinder022_5.geometry} material={nodes.Cylinder022_5.material} />
        <mesh geometry={nodes.Cylinder022_6.geometry} material={materials.ecostress_dexter} />
      </group>
    </group>
  )
}

useGLTF.preload(iss)
