/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as satellite from "satellite.js";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { convertLongLatToXYZ } from "./Helpers";
import { earthRadius } from "satellite.js/lib/constants";

export default function Satellite({ tle1, tle2 }) {
  const satRef = useRef();
  const satRecord = satellite.twoline2satrec(tle1, tle2);
  useFrame(({ clock }) => {
    //let frame = clock.elapsedTime % rate;
    //let point = ellipseCurvePoints.getPointAt(frame / rate);
    let pos = [];
    let positionAndVelocity = satellite.propagate(satRecord, new Date());
    let positionEci = positionAndVelocity.position;
    //console.log("pos eci", positionEci);
    let gmst = satellite.gstime(new Date());

    if (positionEci) {
      let positionGd = satellite.eciToGeodetic(positionEci, gmst);

      // Geodetic coords are accessed via `longitude`, `latitude`,
      let longitude = positionGd.longitude;
      let latitude = positionGd.latitude;
      //console.log("long", longitude, "    ", "latitude", latitude);
      pos = convertLongLatToXYZ(latitude, longitude, earthRadius);
      pos = pos.map((i) => i / 1000);
    }
    satRef.current.position.x = pos[0];
    satRef.current.position.y = pos[1];
    satRef.current.position.z = pos[2];
  });

  return (
    <mesh ref={satRef}>
      <torusGeometry args={[0.0001, 0.2, 12, 36]} />
      <meshStandardMaterial color={"red"} />
    </mesh>
  );
}

useGLTF.preload(satellite);
